label: Use new, optional 'ascent', 'descent' properties
adafruit/Adafruit_CircuitPython_Display_Text pull request #102
Opened 2020-12-05 22:04 UTC by jepler

Each time new glyphs have to be loaded from a font, it can take a long time (hundreds of milliseconds).  In a parallel commit, 'ascent' and 'descent' properties will be added to BDF font objects, are essentially free to compute, and are in any case much quicker than entering load_glyphs.

This may change the layout of text slightly.  For instance, the height of the "M" glyph in GothamBlack-50.bdf is 35, but the Ascent of the font is 40 (and some characters, such as Å, are taller than the ascent at 45 pixels high)

In order to actually be beneficial, https://github.com/adafruit/Adafruit_CircuitPython_Bitmap_Font/pull/31 must also be merged.

This change is only lightly tested, and the code path for font-with-background is entirely untested!

2020-12-29 16:12 UTC, FoamyGuy requested changes
I tested with the forkawesome font and code provided on a PyPortal and that is working well.

Once we handle the one issue with BuiltinFont I think this is good to go.

2020-12-29 16:12 UTC, FoamyGuy commented on adafruit_display_text/label.py
> -        try:
I think we may need to bring back this try / except. 

Attempting to use `terminalio.FONT` (simpletest script) I am getting this error with this version from this PR:
```
Traceback (most recent call last):
  File "code.py", line 7, in <module>
  File "/lib/adafruit_display_text/label.py", line 135, in __init__
  File "/lib/adafruit_display_text/label.py", line 259, in _update_text
  File "/lib/adafruit_display_text/label.py", line 192, in _get_ascent
  File "/lib/adafruit_display_text/label.py", line 181, in _get_ascent_descent
AttributeError: 'BuiltinFont' object has no attribute 'load_glyphs'
```

2020-12-29 16:13 UTC, FoamyGuy commented
I will also follow up with @kmatch98 after this gets merged and we can apply similar changes in the BitmapLabel.

2021-01-08 00:44 UTC, FoamyGuy commented on adafruit_display_text/label.py
> -        try:
I had the right idea in needing to catch an attribute error, but wrong place.  Up inside of `_get_ascent_descent` was the correct place to catch and ignore this error since the built-in font doesn't use that.

2021-01-08 00:48 UTC, FoamyGuy approved these changes
I added a few commits, one that falls back safely for the builtin font. This resolves the issue with simpletest, and any other labels using the builtin font.

One that added extra spaces in a few docstrings inside of `bitmap_label` these lines were otherwise untouched by the PR, but I think it came up due to an update in Sphinx version. Had to update my local tool to replicate and fix.

I tested the current version successfully with the test scripts from this PR and the simpletest in the examples directory

2021-01-08 00:51 UTC, FoamyGuy commented
I would like to get another librarian to take one more quick look at this if possible since I made the final commits.

My full test code with imports and all is:
```python
import board
from displayio import Group
from adafruit_display_text import label
from adafruit_bitmap_font import bitmap_font

font = bitmap_font.load_font("/fonts/forkawesome-36.pcf")
w,h,dx,dy = font.get_bounding_box()

glyphs = "".join(chr(0xf000 + i) for i in range(8))

group = Group()
label = label.Label(font=font, text=glyphs, background_color=0x111111)
label.anchor_point = (0, 0)
label.anchored_position = (0,0)

group.append(label)
board.DISPLAY.show(group)
while True:
    pass
```
This is ready to merge after one more look-over. Thanks in advance!

2021-01-08 18:59 UTC, tannewt approved these changes
Code looks fine to me. I didn't test it.

2021-01-08 21:31 UTC, merged