New parameter and example creation for testing and future reference
adafruit/Adafruit_CircuitPython_Display_Text pull request #115
Opened 2021-02-07 03:54 UTC by jposada202020

With this change, we are adding a new parameter called base_alignment in the label library.  Also we are including some tests to compare old behavior vs New behavior. This will address issues #103 and #100. 
For back-compatibility parameter is set to False by default, that way old code created will still function with the new version

2021-02-13 22:41 UTC, jposada202020 commented
@FoamyGuy 
```
  from adafruit_display_text import label
  import displayio
  from blinka_displayio_pygamedisplay import PyGameDisplay
  from adafruit_bitmap_font import bitmap_font
  import terminalio
  import time
  import random
  
  display = PyGameDisplay(width=320, height=240)
  
  # Create the text label
  main_group = displayio.Group(max_size=18)
  
  # Test parameters
  TEXT_BACKGROUND_COLOR = [0xe0433, 0x990099, 0xd6d714, 0xd73014, 0x1415d7, 0x71646f]
  FONT_TESTS = [bitmap_font.load_font("Fayette-HandwrittenScript-24.bdf"),
                bitmap_font.load_font("LeagueSpartan-Bold-16.bdf"),
                terminalio.FONT]
  TEXT_COLOR = 0x00FF00
  X_COL_POS = [10, 110]  # X position of the Label boxes
  TEST_TEXT = ["aApPqQ.", 'ñúÇèüß']  # Iteration text for testing
  LOCALISATION_Y = [40, 80]  # Y coordinate of the text labels
  NUMBER_TEXT_LABELS = len(LOCALISATION_Y) * len(X_COL_POS)  # Calculation for Display.Group function
  TIME_BETWEEN_TEXTS = 3  # Seconds
  TEST_PADDING_VALUES = [-3, 0, 15]
  TEST_CHOICES = [True, False]
  BASE_ALIGNMENT_OPTIONS = [False, True]
  
  
  for behaviour in BASE_ALIGNMENT_OPTIONS:
      for padding in TEST_PADDING_VALUES:
          for text_test in TEST_TEXT:
              main_group = displayio.Group(max_size=NUMBER_TEXT_LABELS + 1)
              for position in LOCALISATION_Y:
                  text = label.Label(
                      font=FONT_TESTS[0],
                      text=text_test,
                      color=TEXT_COLOR,
                      background_tight=random.choice(TEST_CHOICES),
                      background_color=TEXT_BACKGROUND_COLOR[0],
                      x=X_COL_POS[0],
                      y=position,
                      base_alignment=behaviour,
                  )
                  main_group.append(text)
                  text = label.Label(
                      font=FONT_TESTS[1],
                      text=text_test,
                      color=TEXT_COLOR,
                      background_tight=False,
                      background_color=TEXT_BACKGROUND_COLOR[1],
                      x=X_COL_POS[1],
                      y=position,
                      base_alignment=behaviour,
                  )
                  main_group.append(text)
                  display.show(main_group)
                  display.refresh()
              time.sleep(TIME_BETWEEN_TEXTS)

```

2021-02-13 23:25 UTC, FoamyGuy requested changes
Thanks @jposada202020. I'm not sure what I saw last time but it does seem all good now with the Fayette font.

I think is pretty close to ready. It seems that when I merged the scale PRs it caused merge conflicts here. I think it can be resolved if you merge master into this branch. Let me know if you'd like help though, I'm happy to help out.

I'd like to get a simplified example if we can as well.

After those things I think this is probably good to go! Thanks again for working on this!

2021-02-13 23:25 UTC, FoamyGuy commented on examples/display_text_label_align_baseline_comparison.py
> +# SPDX-FileCopyrightText: 2021 ladyada for Adafruit Industries
You can change the copyright to your name in this example script that you wrote if you are comfortable with that. 

I think we should either add one extra example that is much simpler. or else modify this one to be simpler. I'll leave it up to you. I can see the upside of keeping this one for more comprehensive test.

I think we should provide something like `display_text_label_align_baseline_simpletest.py` that will contain nothing but two labels with different fonts with the new parameter enabled to show how they can easily align with each other.

2021-02-14 01:47 UTC, jposada202020 commented
@FoamyGuy Thanks for the revision, thanks for all the suggestions, For the code, you are right, I was just trying to find where the problem was :) ...I think I will use original code by @endico in issue #103 for the example. And also make the changes as suggested. Thanks for the review. And for your time 👍🏼

2021-02-14 01:48 UTC, jposada202020 commented
...I forgot "it caused merge conflicts here. I think it can be resolved if you merge master into this branch. Let me know if you'd like help though, I'm happy to help out." Yes, I will need help with that. I will ping you when other changes are ready

2021-02-14 03:35 UTC, kmatch98 commented
I ran the example code with a few different font files and it works great!  

The Large font that's in the example wasn't in the repository `fonts` folder.  Maybe add another large version of the LeagueSpartan to include in the repo to highlight this new feature?

2021-02-14 21:24 UTC, FoamyGuy reviewed
Thanks for working on this! I see the conflicts are handled now.

2021-02-14 21:24 UTC, FoamyGuy commented on examples/display_text_label_align_baseline_comparison.py
> +    left_text = label.Label(
instead of creating new labels each iteration in the main loop, lets try to make the labels before the main loop and then either only update which one is showing inside the main loop.  Or if you want you could make 4 labels 2 sets one with the new argument, true and one with it false. Similar to how this comparison example is: https://github.com/adafruit/Adafruit_CircuitPython_Display_Text/blob/master/examples/display_text_label_vs_bitmap_label_comparison.py . If you need some more specific ideas how to do it let me know.

2021-02-14 23:04 UTC, jposada202020 commented
@FoamyGuy I changed the example to include both 4 labels in the screen at all times, Thanks for the comments reviews, and help with this PR.

2021-02-16 00:08 UTC, FoamyGuy approved these changes
I tested these changes successfully on PyPortal and MagTag. Changes look good to me. Thanks for working on this @jposada202020!

Here is how the new example looks on a MagTag:
![image](https://user-images.githubusercontent.com/2406189/108003233-be757880-6fb7-11eb-9b05-13a7e2837873.png)

I changed the big font to one I had available and adjusted the positions slightly to fit the magtag screen better.

2021-02-16 00:19 UTC, jposada202020 commented
@FoamyGuy Team Work!!!! Thanks! You save us some time for the documentation :). Thank you

2021-02-16 01:12 UTC, kmatch98 commented
@jposada202020 this is really helpful. Thanks for adding.  Do you plan to do the same for the bitmap_label version?

2021-02-16 01:46 UTC, jposada202020 commented
@kmatch98 

Yes no problem. I will like to take a look at bitmap_label at the same time to do the Documentation (Including/Excluding features compared with Label) if that is ok?. So give me until the weekend :)

2021-02-19 13:35 UTC, merged