Add typing and documentation for ScrollingLabel
adafruit/Adafruit_CircuitPython_Display_Text pull request #170
Opened 2022-05-11 04:24 UTC by rgrizzell

I noticed it was missing.

2022-05-12 19:42 UTC, tekktrik commented on adafruit_display_text/scrolling_label.py
> +    from fontio import BuiltinFont
Don't have the time to give a full check this instant, but something I noticed that I wanted to mention so this doesn't get merged :)

`fontio` should have `FontProtocol` in it that was created for type annotations to take the place of `Union[BuiltinFont, BDF, PCF]` so we should use that!  I'll double check that this is indeed valid for these type annotations.

2022-05-13 19:23 UTC, tekktrik requested changes
Thanks for the submission, this is great!  I had some feedback, mostly about the use of `Optional` (and some of these are just thank yous :) ).  Let me know if I can help explain anything!

2022-05-13 19:23 UTC, tekktrik commented on adafruit_display_text/scrolling_label.py
> +    from adafruit_bitmap_font.pcf import PCF
You can change this over to use the `fontio.FontProtocol` typing protocol!

```suggestion
    from fontio import FontProtocol
```

2022-05-13 19:23 UTC, tekktrik commented on adafruit_display_text/scrolling_label.py
> +    from typing import Union, Optional
You won't need `Union` anymore if you use `fontio.FontProtocol` either!

```suggestion
    from typing import Optional
```

2022-05-13 19:23 UTC, tekktrik commented on adafruit_display_text/scrolling_label.py
> +        font: Union[BuiltinFont, BDF, PCF],
This can change over to `fontio.FontProtocol`:

```suggestion
        font: FontProtocol,
```

2022-05-13 19:23 UTC, tekktrik commented on adafruit_display_text/scrolling_label.py
> -
Thank you :pray:

2022-05-13 19:23 UTC, tekktrik commented on adafruit_display_text/scrolling_label.py
> +    :type font: ~BuiltinFont, ~BDF, or ~PCF
This can also change to `fontio.FontProtocol`:

```suggestion
    :type: ~FontProtocol
```

2022-05-13 19:23 UTC, tekktrik commented on adafruit_display_text/scrolling_label.py
> +        max_characters: Optional[int] = 10,
So `Optional` is actually a horrible name for what it describes :sweat_smile:  What it denotes is something that can take `None` as a value.  For example if I had an argument for a class that could set the color for something as a hex code, or `None` to signify that it should be transparent, it would be:

```python
def set_color(color: Optional[int]):
    ...
```

It looks like these can't take `None` as a value, so despite being optional to provide, they aren't `Optional`.

In this case, despite being optional to provide, the argument still is/expects to be a `str` type, so it would just be:

```suggestion
        text: str = "",
```

Same for the ones below!

2022-05-13 19:23 UTC, tekktrik commented on adafruit_display_text/scrolling_label.py
> +    def update(self, force: Optional[bool] = False) -> None:
See the previous comment about `Optional`.  `force` should be type annotated as just `bool`.

2022-05-13 19:23 UTC, tekktrik commented on adafruit_display_text/scrolling_label.py
> +    def current_index(self, new_index: int):
If you could add the `None` return type here that would be awesome!

2022-05-13 19:23 UTC, tekktrik commented on adafruit_display_text/scrolling_label.py
>          :return string: The full text of this label.
I know this isn't a part of your PR, but if you wouldn't mind changing this, that would be fantastic!

```suggestion
        :return str: The full text of this label.
```

2022-05-13 19:23 UTC, tekktrik commented on adafruit_display_text/scrolling_label.py
> +    def full_text(self, new_text: str):
You can also add the `None` return type here!

2022-05-13 19:23 UTC, tekktrik commented on docs/api.rst
> +.. automodule:: adafruit_display_text.scrolling_label
Thank you for catching this!

2022-05-17 03:02 UTC, rgrizzell commented on adafruit_display_text/scrolling_label.py
> +    from fontio import BuiltinFont
It appears as if we'll need to include `FontProtocol` in the [Adafruit_Blinka_Displayio](https://github.com/adafruit/Adafruit_Blinka_Displayio/blob/main/fontio.py) library to get the Sphinx Docs to compile with this change.

2022-05-17 03:53 UTC, rgrizzell commented on adafruit_display_text/scrolling_label.py
> +    from fontio import BuiltinFont
I've added the `FontProtocol` class to the Blinka Displayio library and was able to compile the docs after that. The functions are just specified with a simple `pass` and I need to spend a bit more time to determine what, if anything, needs to be included. I'll create an issue and solicit some feedback over there.

In the meantime, you can test using my fork.

```diff
diff --git a/requirements.txt b/requirements.txt
--- a/requirements.txt	(revision 9417ccc6e033d9a77951835b77bc9f050b210380)
+++ b/requirements.txt	(date 1652758810710)
@@ -3,5 +3,5 @@
 # SPDX-License-Identifier: Unlicense
 
 Adafruit-Blinka
-adafruit-blinka-displayio
+git+https://github.com/rgrizzell/Adafruit_Blinka_Displayio@main#egg=adafruit-blinka-displayio
 adafruit-circuitpython-bitmap-font

```

2022-05-17 04:12 UTC, rgrizzell commented
Builds are currently failing until an upstream issue can be resolved.
https://github.com/adafruit/Adafruit_Blinka_Displayio/issues/92

2022-05-18 16:17 UTC, tekktrik requested changes
This should be resolved now.  Can you pin the minimum version of `Adafruit_Blinka_displayio` to 0.10.2 in `setup.py` and `requirements.txt` so that anyone upgrading can grab the update library?  Let me know if you'd like help doing so!

2022-05-19 03:30 UTC, rgrizzell commented
I think that'll do it. Documentation builds nicely with the latest version of adafruit-blinka-displayio. Thanks for adding the typing.

2022-05-19 13:42 UTC, merged