Use supervisor.ticks_ms for scrolling_label animation
adafruit/Adafruit_CircuitPython_Display_Text pull request #208
Opened 2024-06-23 07:34 UTC by RetiredWizard

As described in adafruit/circuitpython#5411 time.monotonic loses precision over time, which eventually causes the scrolling_label animation to occur every time an update method is called. This can result in the scrolling text suddenly speeding up dramatically.

This PR uses supervisor.ticks_ms and adds a bit of logic to watch for the value rolling over instead of time.monotonic() which should resolve the issue. As mentioned  by Dan in the referenced issue, another option would be to use time.monotonic_ns and similarly watch for the rollover, however apparently not all boards support the monotonic_ns method.

2024-06-23 07:52 UTC, RetiredWizard commented
The CI didn't like including supervisor. I don't know if that can be fixed in the requirements/toml/??? files somewhere or if it's a bigger issue with the approach.

2024-06-23 19:05 UTC, FoamyGuy commented
I think the step that is failing is the docs build. If you add `"supervisor"` to the list here: https://github.com/adafruit/Adafruit_CircuitPython_Display_Text/blob/608833a399d21310225c1977c11084927668e732/docs/conf.py#L30 it should be able to complete successfully I think.

2024-06-23 19:24 UTC, RetiredWizard commented
> think the step that is failing is the docs build. If you add `"supervisor"` to the list here:

That did the trick :grin: Thanks!

2024-06-23 22:11 UTC, dhalbert requested changes
> As mentioned by Dan in the referenced issue, another option would be to use time.monotonic_ns and similarly watch for the rollover, however apparently not all boards support the monotonic_ns method.

A small number of SAMD21 ("M0") boards support `displayio`, but don't support longints and therefore don't support `monotonic_ns`.

One issue is that `supervisor.ticks_ms` is not implemented by Blinka, which would make this not usable if used under Blinka.

I think the solution is to use https://github.com/adafruit/Adafruit_CircuitPython_ticks instead of using `supervisor.ticks_ms()` directly. The `adafruit_ticks library` chooses the ticks mechanism based on what is available.

2024-06-24 14:18 UTC, dhalbert commented on adafruit_display_text/scrolling_label.py
>                  self._last_animate_time = _now
You can use `adafruit_ticks.ticks_diff` or `ticks_less` to handle the wraparound automatically. See https://docs.circuitpython.org/projects/ticks/en/latest/api.html and the library code.

2024-06-24 19:25 UTC, dhalbert approved these changes
Looks good, thanks!

2024-06-24 19:25 UTC, merged